# -*- coding: utf-8 -*-
"""Milestone 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QyPTp8o0FU2IO6HMwUiAD82wYi3xXiDz
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.utils import resample

# 1. Load the data
df = pd.read_csv('airline_delay_cleaned.csv')

# 2. Target Definition (Required for splitting context)
df['delay_ratio'] = df['arr_del15'] / df['arr_flights']
df['target'] = (df['delay_ratio'] > 0.15).astype(int)

# 3. SPLIT THE DATASET FIRST (as requested)
# Features we plan to use
features_raw = ['year', 'month', 'carrier', 'airport', 'arr_flights']
X = df[features_raw]
y = df['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 4. ENCODING & FEATURE SELECTION
# We fit the encoders ONLY on the training data to prevent leakage
le_carrier = LabelEncoder()
le_airport = LabelEncoder()

# Create copies to avoid warnings
X_train = X_train.copy()
X_test = X_test.copy()

X_train['carrier_encoded'] = le_carrier.fit_transform(X_train['carrier'])
X_train['airport_encoded'] = le_airport.fit_transform(X_train['airport'])

# Transform test data using the mapping from training
X_test['carrier_encoded'] = X_test['carrier'].map(lambda s: le_carrier.transform([s])[0] if s in le_carrier.classes_ else -1)
X_test['airport_encoded'] = X_test['airport'].map(lambda s: le_airport.transform([s])[0] if s in le_airport.classes_ else -1)

# Final feature selection (removing the original text columns)
final_features = ['year', 'month', 'carrier_encoded', 'airport_encoded', 'arr_flights']
X_train_final = X_train[final_features]
X_test_final = X_test[final_features]

# 5. SAVE CSV (Before Normalization)
train_unscaled = pd.concat([X_train_final, y_train.reset_index(drop=True)], axis=1)
test_unscaled = pd.concat([X_test_final, y_test.reset_index(drop=True)], axis=1)

train_unscaled.to_csv('train_preprocessed_unscaled.csv', index=False)
test_unscaled.to_csv('test_preprocessed_unscaled.csv', index=False)

# 6. NORMALIZATION
scaler = StandardScaler()

# Fit only on training data
X_train_scaled = pd.DataFrame(scaler.fit_transform(X_train_final), columns=final_features)
X_test_scaled = pd.DataFrame(scaler.transform(X_test_final), columns=final_features)

# 7. SAVE CSV (After Normalization)
train_scaled = pd.concat([X_train_scaled, y_train.reset_index(drop=True)], axis=1)
test_scaled = pd.concat([X_test_scaled, y_test.reset_index(drop=True)], axis=1)

train_scaled.to_csv('train_preprocessed_scaled.csv', index=False)
test_scaled.to_csv('test_preprocessed_scaled.csv', index=False)

# 8. HANDLE DATA IMBALANCE (on the training set)
# Class 0 is minority (~41%), Class 1 is majority (~59%) based on previous runs
df_majority = train_scaled[train_scaled.target == 1]
df_minority = train_scaled[train_scaled.target == 0]

# Upsample minority class to match majority
df_minority_upsampled = resample(df_minority,
                                 replace=True,     # sample with replacement
                                 n_samples=len(df_majority),    # to match majority class
                                 random_state=42) # reproducible results

train_balanced = pd.concat([df_majority, df_minority_upsampled])
train_balanced.to_csv('train_preprocessed_balanced.csv', index=False)

print("Files generated:")
print("- train_preprocessed_unscaled.csv")
print("- test_preprocessed_unscaled.csv")
print("- train_preprocessed_scaled.csv")
print("- test_preprocessed_scaled.csv")
print("- train_preprocessed_balanced.csv")

# 8. EDA DIAGRAMS

# Diagram 1: Average Delay Ratio by Carrier
plt.figure(figsize=(10, 8))
carrier_perf = df.groupby('carrier_name')['delay_ratio'].mean().sort_values(ascending=False).reset_index()
sns.barplot(data=carrier_perf, x='delay_ratio', y='carrier_name', palette='viridis')
plt.title('Average Delay Ratio by Carrier')
plt.tight_layout()
plt.savefig('eda_1_carrier_performance.png')

# Diagram 2: Cancellations and Diversions Over Time
cd_data = df.groupby('year')[['arr_cancelled', 'arr_diverted']].sum().reset_index()
plt.figure(figsize=(10, 6))
plt.plot(cd_data['year'], cd_data['arr_cancelled'], marker='o', label='Cancelled', color='red')
plt.plot(cd_data['year'], cd_data['arr_diverted'], marker='s', label='Diverted', color='orange')
plt.title('Total Annual Cancellations vs Diversions')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.7)
plt.savefig('eda_2_cancellation_trend.png')

# Diagram 3: Distribution of Delay Minutes by Reason
reasons = ['carrier_delay', 'weather_delay', 'nas_delay', 'security_delay', 'late_aircraft_delay']
reason_sums = df[reasons].sum()
plt.figure(figsize=(8, 8))
plt.pie(reason_sums, labels=[r.replace('_', ' ').title() for r in reasons], autopct='%1.1f%%', startangle=140)
plt.title('Distribution of Delay Minutes by Reason')
plt.savefig('eda_3_delay_reasons_pie.png')

# Diagram 4: Monthly Delay Trend
plt.figure(figsize=(10, 6))
sns.lineplot(data=df, x='month', y='delay_ratio', marker='o', color='teal')
plt.title('Monthly Delay Ratio Trend')
plt.xticks(range(1, 13))
plt.savefig('eda_4_monthly_trend.png')

# Diagram 5: Heatmap of Carrier vs Month
top_10 = df['carrier'].value_counts().nlargest(10).index
pivot_heatmap = df[df['carrier'].isin(top_10)].pivot_table(index='carrier', columns='month', values='delay_ratio', aggfunc='mean')
plt.figure(figsize=(12, 6))
sns.heatmap(pivot_heatmap, cmap='YlOrRd', annot=True, fmt=".2f")
plt.title('Top 10 Carrier Delay Intensity by Month')
plt.savefig('eda_5_carrier_month_heatmap.png')

print("All steps completed. Files created: train_unscaled.csv, test_unscaled.csv, train_scaled.csv, test_scaled.csv, train_balanced.csv")

import numpy as np

# Generate the Correlation Heatmap
plt.figure(figsize=(12, 10))
# We only use numeric columns as correlation requires numbers
correlation_matrix = df.select_dtypes(include=[np.number]).corr()
sns.heatmap(correlation_matrix, annot=False, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Heatmap of Airline Delay Dataset')
plt.tight_layout()
plt.savefig('correlation_heatmap.png')

# Show the actual correlation values for a few key features for explanation
print("Correlation with arr_del15 (Target-related):")
print(correlation_matrix['arr_del15'].sort_values(ascending=False))